In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import Forecast
import Date

In [5]:
sun = pd.read_csv('Data/oxon_solar_2014.csv', usecols=[1])

In [12]:
daywanted = 150
datewanted = Date.getdatewanted(daywanted, 2014)
solar_variation = sun[0+daywanted*24:24+daywanted*24]
outside_temp_variation, UV = Forecast.forecastF(datewanted)
sunangle = pd.read_csv('Data/January.csv', usecols=[4])
outside_temp_variation = pd.DataFrame(outside_temp_variation)

In [13]:
out_temp = np.array(outside_temp_variation)
sun_var = np.array(solar_variation)
sun_ang = np.array(sunangle.iloc[0:24])

In [14]:
glassthickness = 2*4.8*10**-3
area = 20
k = 0.39
rho = 1.293
V = 220
Cv = 1.004/1.4

In [15]:
in_temp = np.zeros(24)

In [23]:
iteration = 10
n = iteration
qsun = (0.9-0.01*sun_ang[n])*sun_var[n]
qconduct = k*((out_temp[n]-in_temp[n])/glassthickness)/1000
Q = area*(qsun+qconduct)
deltaT = (Q)/(rho*V*Cv)

In [24]:
qconduct

array([0.59244792])

In [25]:
qsun

array([0.3536324])

In [26]:
deltaT

array([0.09275367])